name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] print start-up data"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"
      - name: "[debug] print when triggered from main"
        if: ${{ inputs.debug && github.ref == 'refs/heads/main'}}
        # refs/heads/<branch_name>: branch가 main branch이다
        run: |
          echo "Triggered from main"
      - name: Greeting
        run: |
          echo "Hello, world"
