name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.status}}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT" # 깃헙이 정해주는 ouput file의 path
      - name: Build
        id: build
        run: echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT" # output은 key-value로 준다
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying"
