name: 16 - Working with Environments
# 없으면 커밋메시지로 run-name이 default로 정해짐
# github, inoputs context에 access가능
run-name: 16 - Working with Environments | env - ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        # input으로 사용할 수 있는데, option으로 나올 env들은
        # 깃헙리포든, organization에서든 미리 생성이 되어있어야 한다.
        type: environment
        default: staging

jobs:
  # Staging에서는 Deployment protection rules 정해진게 아무것도 없기 때문에
  # 바로 실행될 것
  deploy-staging:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    env:
      my-env-value: ${{vars.MY_ENV_VALUE || 'defualt value'}}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{env.my-env-value}}"

  # Prod에서는 Deployment protection rules 정해줬기에
  # reviewer, wait timer가 만족해야지만 실행될 것
  deploy-prod:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    env:
      my-env-value: ${{vars.MY_ENV_VALUE || 'defualt value'}}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{env.my-env-value}}"
