name: 16 - Working with Environments

on:
  workflow_dispatch:
    inputs:
      target-env:
        # input으로 사용할 수 있는데, option으로 나올 env들은
        # 깃헙리포든, organization에서든 미리 생성이 되어있어야 한다.
        type: environment
        default: staging

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    # vars context는 깃헙리포, org에서 설정되기때문에 yaml파일에서는 존재여부를 모른다
    # 때문에 바로 vars.MY_ENV_VALUE로 접근하면 squiggly라인이 생기는데, 이를 피하려면
    # job 단계의 env key로 설정하고 default value를 주고,
    # step에서는 var context로 접근하는게 아닌 env context로 접근한다
    env:
      my-env-value: ${{vars.MY_ENV_VALUE || 'defualt value'}}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{env.my-env-value}}"
